name: Build Python App with PyInstaller

on:
  push:
    branches:
      - main  # Trigger the build on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the build on pull requests targeting the main branch

jobs:
  build:
    runs-on: windows-latest  # Specify the operating system to build on (Windows)

    steps:
    - name: Check out repository
      uses: actions/checkout@v3  # Check out the code in the repository

    - name: Set up Python
      uses: actions/setup-python@v4  # Set up the Python environment
      with:
        python-version: '3.10'  # Specify your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --icon=assets/icon.ico app.py  # Build the app with PyInstaller

    - name: Upload executable as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-latest
        path: dist/app.exe  # Path to the built executable
